#!/usr/bin/env bash
set -euo pipefail

### 고정 경로/기본값
# SERVER_IP 는 더 이상 하드코딩 기본값을 쓰지 않음.
# 우선순위: --server-ip / 환경변수 SERVER_IP > dnsmasq(옵션66) 자동감지 > 에러
SERVER_IP="${SERVER_IP:-}"
WWW_ROOT="${WWW_ROOT:-/var/www/html}"
TFTP_CFG="/var/lib/tftpboot/grub.cfg"        # 고정
MNT_POINT="${MNT_POINT:-/mnt}"
EXCLUDE_TOP=("autoinstall" "ks")

usage() {
  cat <<USAGE
Usage:
  $(basename "$0") /path/to/file.iso [--os rocky|ubuntu|rhel|centos|almalinux|ol|oraclelinux|<custom>] [--version X.Y[.Z]

Examples:
  $(basename "$0") /iso/ubuntu-24.04-live-server-amd64.iso --os ubuntu --version 24.04
  $(basename "$0") /iso/Rocky-9.6-x86_64-dvd.iso           --os rocky  --version 9.6
  $(basename "$0") /iso/rhel-9.4-x86_64-dvd.iso            --os rhel   --version 9.4
  $(basename "$0") /iso/CentOS-7-x86_64-DVD-2009.iso       --os centos --version 7
USAGE
}

# --- helpers
has_file() { [[ -f "$1" ]]; }
has_dir()  { [[ -d "$1" ]]; }
append()   { echo -e "$*" >> "$TFTP_CFG"; }

is_excluded_top() {
  local n="${1:-}"
  for ex in "${EXCLUDE_TOP[@]}"; do
    [[ "$n" == "$ex" ]] && return 0
  done
  return 1
}

backup_cfg() {
  [[ -f "$TFTP_CFG" ]] && cp -a "$TFTP_CFG" "${TFTP_CFG}.$(date +%Y%m%d-%H%M%S).bak" || true
}

write_header() {
  cat > "$TFTP_CFG" <<EOF
# Auto-generated by $(basename "$0") on $(date -Is)
insmod efinet
insmod tftp
insmod http

set default=0
set timeout=500

set srv=${SERVER_IP}
set ubuntu_base=http://\${srv}/ubuntu
set autoinstall_base=http://\${srv}/autoinstall
set ks_base=http://\${srv}/ks

# (http) shorthand
set net_default_server=\${srv}

# ---- Dynamic entries below ----
EOF
}

detect_server_ip_from_dnsmasq() {
  # 1) 명시 파일 먼저
  local files=()
  [[ -f /etc/dnsmasq.d/pxe.conf ]] && files+=(/etc/dnsmasq.d/pxe.conf)
  # 2) dnsmasq.d/*.conf 전수 검사
  if compgen -G "/etc/dnsmasq.d/*.conf" > /dev/null; then
    # shellcheck disable=SC2207
    files+=($(ls -1 /etc/dnsmasq.d/*.conf))
  fi
  # 3) 메인 설정 파일도 후보
  [[ -f /etc/dnsmasq.conf ]] && files+=(/etc/dnsmasq.conf)

  local line ip
  for f in "${files[@]}"; do
    [[ -r "$f" ]] || continue
    while IFS= read -r line; do
      line="${line%%#*}"                       # 우측 주석 제거
      [[ -n "${line// }" ]] || continue        # 빈줄 스킵
      # 예: dhcp-option=option:tftp-server,10.0.0.200
      if [[ "$line" =~ dhcp-option[[:space:]]*=[[:space:]]*option:tftp-server[,=:][[:space:]]*([^,[:space:]]+) ]]; then
        ip="${BASH_REMATCH[1]}"
        # 호스트명이면 해석 시도
        if [[ ! "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
          if command -v getent >/dev/null 2>&1; then
            ip="$(getent ahostsv4 "$ip" | awk '{print $1; exit}')"
          fi
        fi
        if [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
          echo "$ip"
          return 0
        fi
      fi
    done < "$f"
  done
  return 1
}

# --- parse args
ISO_PATH=""
OS_NAME=""
OS_VER=""
while (( "$#" )); do
  case "${1:-}" in
    --os)        OS_NAME="${2:-}"; shift 2;;
    --version)   OS_VER="${2:-}"; shift 2;;
    --server-ip) SERVER_IP="${2:-}"; shift 2;;
    --www-root)  WWW_ROOT="${2:-}"; shift 2;;
    -h|--help)   usage; exit 0;;
    *)
      if [[ -z "$ISO_PATH" ]]; then ISO_PATH="$1"; shift; else echo "Unknown arg: $1"; usage; exit 1; fi
      ;;
  esac
done

if [[ -z "${ISO_PATH}" || ! -f "${ISO_PATH}" ]]; then
  echo "ERROR: ISO file missing: ${ISO_PATH:-<empty>}"; usage; exit 1
fi

# --- SERVER_IP 결정: 인자/환경변수 없으면 dnsmasq(옵션 66)에서 자동 감지
if [[ -z "${SERVER_IP}" ]]; then
  if ip_auto="$(detect_server_ip_from_dnsmasq 2>/dev/null || true)"; then
    SERVER_IP="$ip_auto"
  fi
fi
# 최종 검증: 없으면 에러
if [[ -z "${SERVER_IP}" ]]; then
  echo "ERROR: SERVER_IP 를 결정하지 못했습니다."
  echo " - 방법1: --server-ip <IP> 로 명시 지정"
  echo " - 방법2: /etc/dnsmasq.d/pxe.conf 에 'dhcp-option=option:tftp-server,<IP>' 설정 후 재시도"
  exit 1
fi

# --- infer os/version from filename if needed
ISO_BASENAME="$(basename -- "$ISO_PATH")"
LOWER_NAME="$(echo "$ISO_BASENAME" | tr '[:upper:]' '[:lower:]')"

if [[ -z "${OS_NAME}" ]]; then
  if   [[ "$LOWER_NAME" =~ ^ubuntu-([0-9]{2})\.([0-9]{2}) ]]; then
    OS_NAME="ubuntu";    [[ -z "${OS_VER}" ]] && OS_VER="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
  elif [[ "$LOWER_NAME" =~ ^rocky-([0-9]+)\.([0-9]+) ]]; then
    OS_NAME="rocky";     [[ -z "${OS_VER}" ]] && OS_VER="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
  elif [[ "$LOWER_NAME" =~ ^rhel-([0-9]+)\.([0-9]+) ]]; then
    OS_NAME="rhel";      [[ -z "${OS_VER}" ]] && OS_VER="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
  elif [[ "$LOWER_NAME" =~ ^centos-([0-9]+) ]]; then
    OS_NAME="centos";    [[ -z "${OS_VER}" ]] && OS_VER="${BASH_REMATCH[1]}"
  elif [[ "$LOWER_NAME" =~ ^almalinux-([0-9]+)\.([0-9]+) ]]; then
    OS_NAME="almalinux"; [[ -z "${OS_VER}" ]] && OS_VER="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
  elif [[ "$LOWER_NAME" =~ ^ol-([0-9]+)\.([0-9]+) || "$LOWER_NAME" =~ ^oraclelinux-([0-9]+)\.([0-9]+) ]]; then
    OS_NAME="ol";        [[ -z "${OS_VER}" ]] && OS_VER="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
  else
    echo "WARN: Could not infer --os from filename. Please supply --os and --version."
  fi
fi
if [[ -z "${OS_VER}" ]]; then
  if   [[ "$LOWER_NAME" =~ ([0-9]+)\.([0-9]+) ]]; then
    OS_VER="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
  elif [[ "$LOWER_NAME" =~ ([0-9]+) ]]; then
    OS_VER="${BASH_REMATCH[1]}"
  else
    echo "WARN: Could not infer --version. Please supply --version."
  fi
fi
if [[ -z "${OS_NAME}" || -z "${OS_VER}" ]]; then
  echo "ERROR: --os and --version are required (auto-detect failed)."; exit 1
fi

DEST_DIR="${WWW_ROOT}/${OS_NAME}/${OS_VER}"
mkdir -p "${DEST_DIR}"

echo ">> ISO:       ${ISO_PATH}"
echo ">> OS:        ${OS_NAME}"
echo ">> Version:   ${OS_VER}"
echo ">> Copy to:   ${DEST_DIR}"
echo ">> Mount at:  ${MNT_POINT}"

# --- ISO 파일을 대상 디렉터리에 '복사' (심볼릭 링크 사용 안 함)
cp -av -- "${ISO_PATH}" "${DEST_DIR}/"

# --- mount -> copy contents -> unmount (Anaconda 계열은 repo 트리 필요, Ubuntu도 casper 필요)
if mountpoint -q "${MNT_POINT}"; then
  echo "ERROR: ${MNT_POINT} is already mounted. Unmount it first."; exit 1
fi
mount -o loop,ro -- "${ISO_PATH}" "${MNT_POINT}"
trap 'umount -f "${MNT_POINT}" || true' EXIT

if command -v rsync >/dev/null 2>&1; then
  rsync -aHAX --info=progress2 "${MNT_POINT}/" "${DEST_DIR}/"
else
  cp -avT -- "${MNT_POINT}" "${DEST_DIR}"
fi

if command -v restorecon >/dev/null 2>&1; then
  restorecon -R "${DEST_DIR}" || true
fi

umount "${MNT_POINT}"
trap - EXIT
echo ">> Copy complete."

# ===================== grub.cfg 생성 =====================
backup_cfg
write_header

# --- ANACONDA 공통: repo 트리만 (Rocky/RHEL/CentOS/Alma/Oracle 등)
emit_anaconda_entries_repo_only() {
  local os_key="$1"       # 예: rocky, rhel, centos, almalinux, ol|oraclelinux
  local version="$2"

  local pxeboot_dir="${WWW_ROOT}/${os_key}/${version}/images/pxeboot"
  local vmlinuz="${pxeboot_dir}/vmlinuz"
  local initrd="${pxeboot_dir}/initrd.img"

  [[ -f "$vmlinuz" && -f "$initrd" ]] || return 0

  # Pretty name
  local pretty="$os_key"
  case "$os_key" in
    rocky)          pretty="Rocky Linux" ;;
    rhel)           pretty="RHEL" ;;
    centos)         pretty="CentOS" ;;
    almalinux)      pretty="AlmaLinux" ;;
    ol|oraclelinux) pretty="Oracle Linux" ;;
    *)              pretty="$(tr '[:lower:]' '[:upper:]' <<< ${os_key:0:1})${os_key:1} Linux" ;;
  esac

  append ""
  append "menuentry \"${pretty} ${version}\" {"
  append "    linuxefi (http)/${os_key}/${version}/images/pxeboot/vmlinuz \\"
  append "        ip=dhcp inst.stage2=http://\${srv}/${os_key}/${version} inst.repo=http://\${srv}/${os_key}/${version}"
  append "    initrdefi (http)/${os_key}/${version}/images/pxeboot/initrd.img"
  append "}"

  # Kickstart 자동 노출: /var/www/html/ks/{version}/*.ks 중 첫 번째
  local ks_dir="${WWW_ROOT}/ks/${version}"
  if [[ -d "$ks_dir" ]]; then
    local ks_file=""
    while IFS= read -r -d '' ksf; do ks_file="$(basename "$ksf")"; break; done \
      < <(find "$ks_dir" -maxdepth 1 -type f -name "*.ks" -print0 | sort -z)
    if [[ -n "$ks_file" ]]; then
      append ""
      append "menuentry \"${pretty} ${version} (Kickstart)\" {"
      append "    linuxefi (http)/${os_key}/${version}/images/pxeboot/vmlinuz \\"
      append "        ip=dhcp inst.stage2=http://\${srv}/${os_key}/${version} inst.repo=http://\${srv}/${os_key}/${version} \\"
      append "        inst.ks=\${ks_base}/${version}/${ks_file}"
      append "    initrdefi (http)/${os_key}/${version}/images/pxeboot/initrd.img"
      append "}"
    fi
  fi
}

# --- UBUNTU: ISO Live만 (Autoinstall은 user-data 직접 참조 - cloud-config-url)
emit_ubuntu_entries_iso_only() {
  local version="$1"
  local uburoot="${WWW_ROOT}/ubuntu/${version}"
  local casper_dir="${uburoot}/casper"

  # kernel/initrd: vmlinuz/initrd 우선, 없으면 hwe-*
  local kv="${casper_dir}/vmlinuz"; [[ -f "$kv" ]] || kv="${casper_dir}/hwe-vmlinuz"
  local ki="${casper_dir}/initrd";  [[ -f "$ki" ]] || ki="${casper_dir}/hwe-initrd"

  # 해당 버전 폴더의 첫 번째 ISO(복사본)
  local iso_path=""
  while IFS= read -r -d '' f; do iso_path="$f"; break; done \
    < <(find "${uburoot}" -maxdepth 1 -type f -name "*.iso" -print0 | sort -z)

  [[ -f "$kv" && -f "$ki" && -n "$iso_path" ]] || return 0

  local k_bn; k_bn="$(basename "$kv")"
  local i_bn; i_bn="$(basename "$ki")"
  local iso_name; iso_name="$(basename "$iso_path")"

  # 1) 일반 Live
  append ""
  append "menuentry \"Ubuntu ${version}\" {"
  append "    linuxefi (http)/ubuntu/${version}/casper/${k_bn} \\"
  append "        ip=dhcp url=\${ubuntu_base}/${version}/${iso_name}"
  append "    initrdefi (http)/ubuntu/${version}/casper/${i_bn}"
  append "}"

  # 2) Autoinstall (user-data 직접)
  local seed_dir="${WWW_ROOT}/autoinstall/${version}"
  if [[ -f "${seed_dir}/user-data" ]]; then
    append ""
    append "menuentry \"Ubuntu ${version} (Autoinstall minimal)\" {"
    append "    linuxefi (http)/ubuntu/${version}/casper/${k_bn} \\"
    append "        ip=dhcp url=\${ubuntu_base}/${version}/${iso_name} \\"
    append "        autoinstall cloud-config-url=\${autoinstall_base}/${version}/user-data"
    append "    initrdefi (http)/ubuntu/${version}/casper/${i_bn}"
    append "}"
  fi
}

# --- walk trees and emit
for osdir in "${WWW_ROOT}"/*; do
  [[ -d "$osdir" ]] || continue
  osbase="$(basename "$osdir")"
  is_excluded_top "$osbase" && continue
  case "$osbase" in
    rocky|rhel|centos|almalinux|ol|oraclelinux)
      for vdir in "${osdir}"/*; do
        [[ -d "$vdir" ]] || continue
        ver="$(basename "$vdir")"
        emit_anaconda_entries_repo_only "$osbase" "$ver"
      done
      ;;
    ubuntu)
      for vdir in "${osdir}"/*; do
        [[ -d "$vdir" ]] || continue
        ver="$(basename "$vdir")"
        emit_ubuntu_entries_iso_only "$ver"
      done
      ;;
    *)
      ;;
  esac
done

echo "Generated: $TFTP_CFG"
